name: hlmpn CI Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.22'         # use any Bun 1.2.* version

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24.x'         # use any Node 24.* version

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Lint
        run: bun run lint:ci

      - name: Format check
        run: bun run format

      - name: Typecheck
        run: bun run typecheck

      - name: Build
        run: bun run build

      - name: Run tests
        run: bun run test:ci
